DemoApp228/Controllers/VariantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPOS.DataAccess;
using XPOS.ViewModell;

namespace DemoApp228.Controllers
{
    public class VariantController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return PartialView("_List", VariantRepo.All());
        }
        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            return PartialView("_Create", new VariantViewModel());
        }

        [HttpPost]
        public ActionResult Create(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(int id)
        {
            // id => Category Id
            VariantViewModel model = VariantRepo.byId(id);
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int id)
        {
            // id => Category Id
            VariantViewModel model = VariantRepo.byId(id);
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            return PartialView("_Delete", model);
        }

        [HttpPost]
        public ActionResult Delete(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

DemoApp228/Views/Variant/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <input id="btn-create-new" type="button" class="btn btn-default btn-lg" value="Create New" />
    </div>
    <div class="panel-body">
    </div>

    <!--Table-->
    <div id="data-list">
        Loading...
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "Variant")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        }

        $("#btn-create-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Variant")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Create New");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        });
    </script>
}

DemoApp228/Views/Variant/_Create.cshtml
@model XPOS.ViewModell.VariantViewModel

@using (Html.BeginForm("Create", "Variant", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VariantViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId,
                (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select Category", new
                { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Initial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Save successful! Nama: " + result.entity.Name);
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });
</script>

DemoApp228/Views/Variant/_Delete.cshtml
@model XPOS.ViewModell.VariantViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VariantViewModel</h4>
    <hr />

    @using (Html.BeginForm("Delete", "Variant", FormMethod.Post,
        new { id = "form-delete", name = "form-delete" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>VariantViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CategoryId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CategoryId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Initial)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Initial)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Active)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Active)
            </dd>

        </dl>

            <div class="form-group">
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

<script type="text/javascript">
        $("#form-delete").submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    if (result.success) {
                        alert("Delete successful! Nama: " + result.entity.Name);
                        $(".modal").modal("hide");
                        GetList();
                    } else {
                        alert("error! " + result.message);
                    }
                }
            });
            return false;
        });
</script>

DemoApp228/Views/Variant/_Edit.cshtml
@model XPOS.ViewModell.VariantViewModel

@using (Html.BeginForm("Edit", "Variant", FormMethod.Post,
    new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>VariantViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId,
                (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select Category", new
                { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Initial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Save successful! Nama: " + result.entity.Name);
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });
</script>

DemoApp228/Views/Variant/_List.cshtml
@model IEnumerable<XPOS.ViewModell.VariantViewModel>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Initial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.CategoryId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Initial)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Active)
    </td>

    <td>
        <div class="btn-group btn-group-sm">
            <button type="button" class="btn btn-warning btn-edit" data-id="@item.Id"
                    title="Edit">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-warning btn-delete" data-id="@item.Id"
                    title="Delete">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </button>
        </div>
    </td>

</tr>

}

</table>

<script type="text/javascript">
    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Variant")',
            type: 'get',
            data: { id: $(this).attr("data-id")},
            success: function (result) {
                $(".modal-title").html("Edit");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });
     $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Variant")',
            type: 'get',
            data: { id: $(this).attr("data-id")},
            success: function (result) {
                $(".modal-title").html("Delete");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });
</script>